name: gamma-assets

services:
  assets:
    container_name: gamma-util-assets
    build:
      dockerfile: Dockerfile
    networks:
      - gamma-network

networks:
  gamma-network:
    external: true